# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['TWO_EIGHT.py'],
             pathex=['C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
a.datas += [('1_of_spades.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\1_of_spades.png',"DATA"),
             ('2_of_spades.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\2_of_spades.png',"DATA"),
             ('3_of_spades.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\3_of_spades.png',"DATA"),
             ('4_of_spades.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\4_of_spades.png',"DATA"),
             ('5_of_spades.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\5_of_spades.png',"DATA"),
             ('6_of_spades.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\6_of_spades.png',"DATA"),
             ('7_of_spades.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\7_of_spades.png',"DATA"),
             ('8_of_spades.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\8_of_spades.png',"DATA"),
             ('9_of_spades.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\9_of_spades.png',"DATA"),
             ('10_of_spades.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\10_of_spades.png',"DATA"),
             ('1_of_diamonds.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\1_of_diamonds.png',"DATA"),
             ('2_of_diamonds.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\2_of_diamonds.png',"DATA"),
             ('3_of_diamonds.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\3_of_diamonds.png',"DATA"),
             ('4_of_diamonds.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\4_of_diamonds.png',"DATA"),
             ('5_of_diamonds.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\5_of_diamonds.png',"DATA"),
             ('6_of_diamonds.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\6_of_diamonds.png',"DATA"),
             ('7_of_diamonds.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\7_of_diamonds.png',"DATA"),
             ('8_of_diamonds.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\8_of_diamonds.png',"DATA"),
             ('9_of_diamonds.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\9_of_diamonds.png',"DATA"),
             ('10_of_diamonds.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\10_of_diamonds.png',"DATA"),
             ('1_of_hearts.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\1_of_hearts.png',"DATA"),
             ('2_of_hearts.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\2_of_hearts.png',"DATA"),
             ('3_of_hearts.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\3_of_hearts.png',"DATA"),
             ('4_of_hearts.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\4_of_hearts.png',"DATA"),
             ('5_of_hearts.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\5_of_hearts.png',"DATA"),
             ('6_of_hearts.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\6_of_hearts.png',"DATA"),
             ('7_of_hearts.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\7_of_hearts.png',"DATA"),
             ('8_of_hearts.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\8_of_hearts.png',"DATA"),
             ('9_of_hearts.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\9_of_hearts.png',"DATA"),
             ('10_of_hearts.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\10_of_hearts.png',"DATA"),
             ('1_of_clubs.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\1_of_clubs.png',"DATA"),
             ('2_of_clubs.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\2_of_clubs.png',"DATA"),
             ('3_of_clubs.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\3_of_clubs.png',"DATA"),
             ('4_of_clubs.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\4_of_clubs.png',"DATA"),
             ('5_of_clubs.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\5_of_clubs.png',"DATA"),
             ('6_of_clubs.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\6_of_clubs.png',"DATA"),
             ('7_of_clubs.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\7_of_clubs.png',"DATA"),
             ('8_of_clubs.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\8_of_clubs.png',"DATA"),
             ('9_of_clubs.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\9_of_clubs.png',"DATA"),
             ('10_of_clubs.png','C:\\Users\\xuyan\\PycharmProjects\\TWO_EIGHT\\10_of_clubs.png',"DATA")]
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='TWO_EIGHT',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False,
          icon='twoeighticon.ico') # you can set it True ,
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='TWO_EIGHT')
